In [9]:
# import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [11]:
# load dataset
df = pd.read_csv("Traffic_Crashes_-_Crashes_20250920.csv")
df.head()

,CRASH_RECORD_ID,CRASH_DATE_EST_I,CRASH_DATE,POSTED_SPEED_LIMIT,TRAFFIC_CONTROL_DEVICE,DEVICE_CONDITION,WEATHER_CONDITION,LIGHTING_CONDITION,FIRST_CRASH_TYPE,TRAFFICWAY_TYPE,...,INJURIES_NON_INCAPACITATING,INJURIES_REPORTED_NOT_EVIDENT,INJURIES_NO_INDICATION,INJURIES_UNKNOWN,CRASH_HOUR,CRASH_DAY_OF_WEEK,CRASH_MONTH,LATITUDE,LONGITUDE,LOCATION
0,6e01f9a196d538a9966e07b77571aa2c16ed0934d70d6a...,NaN,09/20/2025 02:12:00 AM,35,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,NOT DIVIDED,...,0.0,0.0,1.0,0.0,2,7,9,42.022660,-87.676647,POINT (-87.67664723812 42.022660268078)
1,58611df156f261acca8dbc3f4d52708c77ab3cd6e50b7d...,Y,09/20/2025 01:05:00 AM,25,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE OPPOSITE DIRECTION,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,2.0,0.0,1,7,9,41.773080,-87.615393,POINT (-87.615392621573 41.773080310407)
2,72cab98be7a0bc8fd2878a44caa73db237b3c1915d8bf5...,NaN,09/20/2025 01:00:00 AM,35,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",OTHER OBJECT,NOT DIVIDED,...,0.0,0.0,2.0,0.0,1,7,9,41.799166,-87.723186,POINT (-87.723186126595 41.7991664566)
3,e248ec4673b109000e7d73cb81a2d7cebf23a6fa127f5d...,NaN,09/20/2025 12:03:00 AM,30,TRAFFIC SIGNAL,FUNCTIONING PROPERLY,CLEAR,"DARKNESS, LIGHTED ROAD",HEAD ON,DIVIDED - W/MEDIAN (NOT RAISED),...,0.0,0.0,8.0,0.0,0,7,9,41.807530,-87.743297,POINT (-87.743296821242 41.807530372894)
4,8f692b1a9bd229f17a36d4a4db99a026223c4c98e66e70...,NaN,09/19/2025 11:30:00 PM,40,NO CONTROLS,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,DIVIDED - W/MEDIAN BARRIER,...,0.0,0.0,1.0,0.0,23,6,9,41.845343,-87.610998,POINT (-87.610998044537 41.845342867304)

In [15]:
# check the shape of our dataset
print(f"This dataset has {df.shape[0]} rows and {df.shape[1]} columns")

This dataset has 986133 rows and 48 columns

In [19]:
# what are the datasets columns
df.columns

Index(['CRASH_RECORD_ID', 'CRASH_DATE_EST_I', 'CRASH_DATE',
       'POSTED_SPEED_LIMIT', 'TRAFFIC_CONTROL_DEVICE', 'DEVICE_CONDITION',
       'WEATHER_CONDITION', 'LIGHTING_CONDITION', 'FIRST_CRASH_TYPE',
       'TRAFFICWAY_TYPE', 'LANE_CNT', 'ALIGNMENT', 'ROADWAY_SURFACE_COND',
       'ROAD_DEFECT', 'REPORT_TYPE', 'CRASH_TYPE', 'INTERSECTION_RELATED_I',
       'NOT_RIGHT_OF_WAY_I', 'HIT_AND_RUN_I', 'DAMAGE', 'DATE_POLICE_NOTIFIED',
       'PRIM_CONTRIBUTORY_CAUSE', 'SEC_CONTRIBUTORY_CAUSE', 'STREET_NO',
       'STREET_DIRECTION', 'STREET_NAME', 'BEAT_OF_OCCURRENCE',
       'PHOTOS_TAKEN_I', 'STATEMENTS_TAKEN_I', 'DOORING_I', 'WORK_ZONE_I',
       'WORK_ZONE_TYPE', 'WORKERS_PRESENT_I', 'NUM_UNITS',
       'MOST_SEVERE_INJURY', 'INJURIES_TOTAL', 'INJURIES_FATAL',
       'INJURIES_INCAPACITATING', 'INJURIES_NON_INCAPACITATING',
       'INJURIES_REPORTED_NOT_EVIDENT', 'INJURIES_NO_INDICATION',
       'INJURIES_UNKNOWN', 'CRASH_HOUR', 'CRASH_DAY_OF_WEEK', 'CRASH_MONTH',
       'LATITUDE', 'LONGITUDE', 'LOCATION'],
      dtype='object')

**Observation:**

Looks like the data columns may need to be changed to lower case for easier data manipulation

In [24]:
# check each columns information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 986133 entries, 0 to 986132
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   CRASH_RECORD_ID                986133 non-null  object
 1   CRASH_DATE_EST_I               71838 non-null   object
 2   CRASH_DATE                     986133 non-null  object
 3   POSTED_SPEED_LIMIT             986133 non-null  int64
 4   TRAFFIC_CONTROL_DEVICE         986133 non-null  object
 5   DEVICE_CONDITION               986133 non-null  object
 6   WEATHER_CONDITION              986133 non-null  object
 7   LIGHTING_CONDITION             986133 non-null  object
 8   FIRST_CRASH_TYPE               986133 non-null  object
 9   TRAFFICWAY_TYPE                986133 non-null  object
 10  LANE_CNT                       199029 non-null  object
 11  ALIGNMENT                      986133 non-null  object
 12  ROADWAY_SURFACE_COND           986133 non-null  object
 13  ROAD_DEFECT                    986133 non-null  object
 14  REPORT_TYPE                    953815 non-null  object
 15  CRASH_TYPE                     986133 non-null  object
 16  INTERSECTION_RELATED_I         226644 non-null  object
 17  NOT_RIGHT_OF_WAY_I             44411 non-null   object
 18  HIT_AND_RUN_I                  309408 non-null  object
 19  DAMAGE                         986133 non-null  object
 20  DATE_POLICE_NOTIFIED           986133 non-null  object
 21  PRIM_CONTRIBUTORY_CAUSE        986133 non-null  object
 22  SEC_CONTRIBUTORY_CAUSE         986133 non-null  object
 23  STREET_NO                      986133 non-null  int64
 24  STREET_DIRECTION               986129 non-null  object
 25  STREET_NAME                    986132 non-null  object
 26  BEAT_OF_OCCURRENCE             986128 non-null  float64
 27  PHOTOS_TAKEN_I                 13916 non-null   object
 28  STATEMENTS_TAKEN_I             23304 non-null   object
 29  DOORING_I                      3147 non-null    object
 30  WORK_ZONE_I                    5392 non-null    object
 31  WORK_ZONE_TYPE                 4124 non-null    object
 32  WORKERS_PRESENT_I              1383 non-null    object
 33  NUM_UNITS                      986133 non-null  int64
 34  MOST_SEVERE_INJURY             983980 non-null  object
 35  INJURIES_TOTAL                 983994 non-null  float64
 36  INJURIES_FATAL                 983994 non-null  float64
 37  INJURIES_INCAPACITATING        983994 non-null  float64
 38  INJURIES_NON_INCAPACITATING    983994 non-null  float64
 39  INJURIES_REPORTED_NOT_EVIDENT  983994 non-null  float64
 40  INJURIES_NO_INDICATION         983994 non-null  float64
 41  INJURIES_UNKNOWN               983994 non-null  float64
 42  CRASH_HOUR                     986133 non-null  int64
 43  CRASH_DAY_OF_WEEK              986133 non-null  int64
 44  CRASH_MONTH                    986133 non-null  int64
 45  LATITUDE                       978712 non-null  float64
 46  LONGITUDE                      978712 non-null  float64
 47  LOCATION                       978712 non-null  object
dtypes: float64(10), int64(6), object(32)
memory usage: 361.1+ MB

In [28]:
# check columns unique values
df.nunique()

CRASH_RECORD_ID                  986133
CRASH_DATE_EST_I                      2
CRASH_DATE                       650971
POSTED_SPEED_LIMIT                   46
TRAFFIC_CONTROL_DEVICE               19
DEVICE_CONDITION                      8
WEATHER_CONDITION                    12
LIGHTING_CONDITION                    6
FIRST_CRASH_TYPE                     18
TRAFFICWAY_TYPE                      20
LANE_CNT                             61
ALIGNMENT                             6
ROADWAY_SURFACE_COND                  7
ROAD_DEFECT                           7
REPORT_TYPE                           3
CRASH_TYPE                            2
INTERSECTION_RELATED_I                2
NOT_RIGHT_OF_WAY_I                    2
HIT_AND_RUN_I                         2
DAMAGE                                3
DATE_POLICE_NOTIFIED             746563
PRIM_CONTRIBUTORY_CAUSE              40
SEC_CONTRIBUTORY_CAUSE               40
STREET_NO                         11934
STREET_DIRECTION                      4
STREET_NAME                        1664
BEAT_OF_OCCURRENCE                  276
PHOTOS_TAKEN_I                        2
STATEMENTS_TAKEN_I                    2
DOORING_I                             2
WORK_ZONE_I                           2
WORK_ZONE_TYPE                        4
WORKERS_PRESENT_I                     2
NUM_UNITS                            17
MOST_SEVERE_INJURY                    5
INJURIES_TOTAL                       20
INJURIES_FATAL                        5
INJURIES_INCAPACITATING              10
INJURIES_NON_INCAPACITATING          20
INJURIES_REPORTED_NOT_EVIDENT        14
INJURIES_NO_INDICATION               50
INJURIES_UNKNOWN                      1
CRASH_HOUR                           24
CRASH_DAY_OF_WEEK                     7
CRASH_MONTH                          12
LATITUDE                         338426
LONGITUDE                        338423
LOCATION                         338454
dtype: int64

In [30]:
# check missingness of data
df.isnull().sum()

CRASH_RECORD_ID                       0
CRASH_DATE_EST_I                 914295
CRASH_DATE                            0
POSTED_SPEED_LIMIT                    0
TRAFFIC_CONTROL_DEVICE                0
DEVICE_CONDITION                      0
WEATHER_CONDITION                     0
LIGHTING_CONDITION                    0
FIRST_CRASH_TYPE                      0
TRAFFICWAY_TYPE                       0
LANE_CNT                         787104
ALIGNMENT                             0
ROADWAY_SURFACE_COND                  0
ROAD_DEFECT                           0
REPORT_TYPE                       32318
CRASH_TYPE                            0
INTERSECTION_RELATED_I           759489
NOT_RIGHT_OF_WAY_I               941722
HIT_AND_RUN_I                    676725
DAMAGE                                0
DATE_POLICE_NOTIFIED                  0
PRIM_CONTRIBUTORY_CAUSE               0
SEC_CONTRIBUTORY_CAUSE                0
STREET_NO                             0
STREET_DIRECTION                      4
STREET_NAME                           1
BEAT_OF_OCCURRENCE                    5
PHOTOS_TAKEN_I                   972217
STATEMENTS_TAKEN_I               962829
DOORING_I                        982986
WORK_ZONE_I                      980741
WORK_ZONE_TYPE                   982009
WORKERS_PRESENT_I                984750
NUM_UNITS                             0
MOST_SEVERE_INJURY                 2153
INJURIES_TOTAL                     2139
INJURIES_FATAL                     2139
INJURIES_INCAPACITATING            2139
INJURIES_NON_INCAPACITATING        2139
INJURIES_REPORTED_NOT_EVIDENT      2139
INJURIES_NO_INDICATION             2139
INJURIES_UNKNOWN                   2139
CRASH_HOUR                            0
CRASH_DAY_OF_WEEK                     0
CRASH_MONTH                           0
LATITUDE                           7421
LONGITUDE                          7421
LOCATION                           7421
dtype: int64

**Observation**

From this we can see columns such as `CRASH_DATE_EST_I`, `LANE_CNT`, `INTERSECTION_RELATED_I`, `NOT_RIGHT_OF_WAY_I` among others have a large number of missing values. We may be most likely forced to drop them because they will not offer us much information.

In [37]:
# check numerical data
df.describe().T

,count,mean,std,min,25%,50%,75%,max
POSTED_SPEED_LIMIT,986133.0,28.423503,6.060047,0.000000,30.000000,30.000000,30.000000,99.00000
STREET_NO,986133.0,3686.408691,2873.418010,0.000000,1257.000000,3201.000000,5555.000000,451100.00000
BEAT_OF_OCCURRENCE,986128.0,1247.382479,704.688551,111.000000,722.000000,1213.000000,1822.000000,6100.00000
NUM_UNITS,986133.0,2.035136,0.449867,1.000000,2.000000,2.000000,2.000000,18.00000
INJURIES_TOTAL,983994.0,0.197298,0.576793,0.000000,0.000000,0.000000,0.000000,21.00000
INJURIES_FATAL,983994.0,0.001155,0.036871,0.000000,0.000000,0.000000,0.000000,4.00000
INJURIES_INCAPACITATING,983994.0,0.019362,0.162867,0.000000,0.000000,0.000000,0.000000,10.00000
INJURIES_NON_INCAPACITATING,983994.0,0.109727,0.426473,0.000000,0.000000,0.000000,0.000000,21.00000
INJURIES_REPORTED_NOT_EVIDENT,983994.0,0.067053,0.333686,0.000000,0.000000,0.000000,0.000000,19.00000
INJURIES_NO_INDICATION,983994.0,1.997930,1.155567,0.000000,1.000000,2.000000,2.000000,61.00000
INJURIES_UNKNOWN,983994.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
CRASH_HOUR,986133.0,13.196288,5.573177,0.000000,9.000000,14.000000,17.000000,23.00000
CRASH_DAY_OF_WEEK,986133.0,4.119930,1.979178,1.000000,2.000000,4.000000,6.000000,7.00000
CRASH_MONTH,986133.0,6.626762,3.365218,1.000000,4.000000,7.000000,9.000000,12.00000
LATITUDE,978712.0,41.855222,0.349268,0.000000,41.783966,41.875150,41.924750,42.02278
LONGITUDE,978712.0,-87.673294,0.711448,-87.939678,-87.721794,-87.674357,-87.633774,0.00000

In [39]:
# check categorical variables
df.describe(include="O").T

,count,unique,top,freq
CRASH_RECORD_ID,986133,986133,6e01f9a196d538a9966e07b77571aa2c16ed0934d70d6a...,1
CRASH_DATE_EST_I,71838,2,Y,62652
CRASH_DATE,986133,650971,02/06/2025 08:00:00 AM,37
TRAFFIC_CONTROL_DEVICE,986133,19,NO CONTROLS,555971
DEVICE_CONDITION,986133,8,NO CONTROLS,562957
WEATHER_CONDITION,986133,12,CLEAR,775998
LIGHTING_CONDITION,986133,6,DAYLIGHT,634616
FIRST_CRASH_TYPE,986133,18,PARKED MOTOR VEHICLE,227705
TRAFFICWAY_TYPE,986133,20,NOT DIVIDED,422109
LANE_CNT,199029.0,61.0,2.0,73424.0
ALIGNMENT,986133,6,STRAIGHT AND LEVEL,963284
ROADWAY_SURFACE_COND,986133,7,DRY,728384
ROAD_DEFECT,986133,7,NO DEFECTS,776986
REPORT_TYPE,953815,3,NOT ON SCENE (DESK REPORT),533568
CRASH_TYPE,986133,2,NO INJURY / DRIVE AWAY,719447
INTERSECTION_RELATED_I,226644,2,Y,215817
NOT_RIGHT_OF_WAY_I,44411,2,Y,40334
HIT_AND_RUN_I,309408,2,Y,296146
DAMAGE,986133,3,"OVER $1,500",629346
DATE_POLICE_NOTIFIED,986133,746563,10/12/2020 04:00:00 PM,12
PRIM_CONTRIBUTORY_CAUSE,986133,40,UNABLE TO DETERMINE,387443
SEC_CONTRIBUTORY_CAUSE,986133,40,NOT APPLICABLE,407907
STREET_DIRECTION,986129,4,W,353802
STREET_NAME,986132,1664,WESTERN AVE,27005
PHOTOS_TAKEN_I,13916,2,Y,10484
STATEMENTS_TAKEN_I,23304,2,Y,19133
DOORING_I,3147,2,Y,2115
WORK_ZONE_I,5392,2,Y,4124
WORK_ZONE_TYPE,4124,4,CONSTRUCTION,2862
WORKERS_PRESENT_I,1383,2,Y,1227
MOST_SEVERE_INJURY,983980,5,NO INDICATION OF INJURY,843371
LOCATION,978712,338454,POINT (-87.905309125103 41.976201139024),1603

In [67]:
# check how long our data spans
df["CRASH_DATE"] = pd.to_datetime(df["CRASH_DATE"])

print(f"This dataset records our first incident on {df['CRASH_DATE'].min().date()} all the way to {df['CRASH_DATE'].max().date()}")

# records by year
print("\n")
print(df['CRASH_DATE'].dt.year.value_counts().sort_index())

This dataset records our first incident on 2013-03-03 all the way to 2025-09-20


CRASH_DATE
2013         2
2014         6
2015      9831
2016     44297
2017     83786
2018    118951
2019    117764
2020     92095
2021    108766
2022    108411
2023    110752
2024    112050
2025     79422
Name: count, dtype: int64

**Observation**

We can see that 2013 and 2014 have 2 and 6 respectively which may not an accurate indication of the events of those years. The rest of the years numbers seem relatively highly balanced